In [2]:
import torch

# empty function - memory allocate

In [ ]:
aa=torch.empty(2,3)

In [11]:
a

tensor([[-1.1458e-13,  1.8623e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [10]:
type(a)

torch.Tensor

In [ ]:
# using zero 
# tensor zero like when we create NN each neuron bais value zero if we want to create starting bais 0
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# rand = random value from 0 to 1 randomly  weight initialization technique
# if we want random value we use this 
torch.rand(2,3)

tensor([[0.2867, 0.3334, 0.8847],
        [0.2442, 0.6252, 0.4078]])

In [ ]:
#maual_Seed = rand use random value but if we use manaul_seed then 
# every time using that seed that values remain same 
# reproduct
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [26]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [27]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor shapes

In [30]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [32]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [31]:
x.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Datatypes

In [37]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [38]:
x.dtype

torch.int64

In [39]:
type(x)

torch.Tensor

In [42]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [44]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [3., 4., 5.]])

# Mathmatical OPeration

In [53]:
# scaler 
torch.manual_seed(10)
x=torch.rand(2,2)
x


tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [54]:
x+2

tensor([[2.4581, 2.4829],
        [2.3125, 2.6150]])

In [55]:
x-2

tensor([[-1.5419, -1.5171],
        [-1.6875, -1.3850]])

In [56]:
x/2

tensor([[0.2290, 0.2414],
        [0.1562, 0.3075]])

In [57]:
x*100

tensor([[45.8085, 48.2857],
        [31.2498, 61.5022]])

In [58]:
x**2

tensor([[0.2098, 0.2332],
        [0.0977, 0.3783]])

In [74]:
## Reduction Operation 
b=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
b

tensor([[2., 0., 9.],
        [9., 4., 4.]])

In [75]:
torch.sum(b)

tensor(28.)

In [76]:
#of one columns
torch.sum(b,dim=0)

tensor([11.,  4., 13.])

In [77]:
#of one columns
torch.sum(b,dim=1)

tensor([11., 17.])

In [78]:
torch.mean(b)

tensor(4.6667)

In [80]:
torch.std(b)

tensor(3.6697)

In [81]:
torch.var(b)

tensor(13.4667)

In [ ]:
# gives the position of max values 
torch.argmax(b)

tensor(2)

In [83]:
torch.argmin(b)

tensor(1)

# Matrix Operation 

In [88]:
f=torch.randint(size=(2,3),low=0 , high=10)
g=torch.randint(size=(3,2),low=0 , high=10)
print(f)
print(g)

tensor([[1, 9, 2],
        [1, 2, 9]])
tensor([[7, 2],
        [9, 4],
        [4, 9]])


In [89]:
#Matrix multiplication 
torch.matmul(f,g)

tensor([[96, 56],
        [61, 91]])

In [94]:
#dot product 

vector1=torch.tensor([2,3])
vector2=torch.tensor([2,3])

In [95]:
torch.dot(vector1,vector2)

tensor(13)

In [98]:
h=torch.randint(size=(3,3),high=10,low=0,dtype=torch.float32)

In [ ]:
#determinant  only on square matrix 
torch.det(h)

tensor(54.0000)

In [100]:
torch.inverse(h)

tensor([[-0.6667,  0.6667, -0.1111],
        [ 0.3333, -0.3333,  0.2222],
        [ 0.3889, -0.2222, -0.0741]])

# Special Function 

In [109]:
k=torch.randint(size=(3,3),high=10,low=0,dtype=torch.float32)

In [110]:
k

tensor([[8., 4., 2.],
        [6., 3., 5.],
        [1., 4., 4.]])

In [111]:
#log
torch.log(k)

tensor([[2.0794, 1.3863, 0.6931],
        [1.7918, 1.0986, 1.6094],
        [0.0000, 1.3863, 1.3863]])

In [112]:
#exp
torch.exp(k)

tensor([[2.9810e+03, 5.4598e+01, 7.3891e+00],
        [4.0343e+02, 2.0086e+01, 1.4841e+02],
        [2.7183e+00, 5.4598e+01, 5.4598e+01]])

In [113]:
torch.sigmoid(k)

tensor([[0.9997, 0.9820, 0.8808],
        [0.9975, 0.9526, 0.9933],
        [0.7311, 0.9820, 0.9820]])

In [114]:
torch.sqrt(k)

tensor([[2.8284, 2.0000, 1.4142],
        [2.4495, 1.7321, 2.2361],
        [1.0000, 2.0000, 2.0000]])

In [115]:
torch.softmax(k,dim=0)

tensor([[8.8009e-01, 4.2232e-01, 3.5119e-02],
        [1.1911e-01, 1.5536e-01, 7.0538e-01],
        [8.0254e-04, 4.2232e-01, 2.5950e-01]])

In [116]:
torch.softmax(k,dim=1)

tensor([[0.9796, 0.0179, 0.0024],
        [0.7054, 0.0351, 0.2595],
        [0.0243, 0.4879, 0.4879]])

In [117]:
torch.relu(k)

tensor([[8., 4., 2.],
        [6., 3., 5.],
        [1., 4., 4.]])

### Tensor Operation on GPU

In [119]:
torch.cuda.is_available()

False

## Reshaping Tensor 

In [122]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [124]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])