In [1]:
import torch 
import nltk 
import numpy as np 
import pandas as pd 
import torch.nn as nn 
from nltk.tokenize import word_tokenize
from collections import Counter


In [2]:
document='''SUYOG KARKI
PROFILE Data Science Intern Candidate  | ML & Analytics suyogkarki2@gmail.com 	 	+977 9860103707 	 	Tokha, Kathmandu linkedin.com/in/suyog-karki-8544a033a 	 	github.com/suyogkarki1 	 	suyogkarki1.com.np 
EDUCATION Data Science student experienced in building end-to-end machine learning projects using Python, SQL, and Scikit-learn covering data cleaning, EDA, feature engineering, statistical testing, preprocessing pipeline, crossvalidation, hyperparameter tuning, and model evaluation. Applied this across projects in weather forecasting, customer churn, and healthcare risk. I'm genuinely curious about AI and machine learning, and I want to keep getting better at it — looking for a data science/ML or analytics internship to learn and grow.
Higher Secondary Education (+2) - Science, 
Kathmandu Model College (KMC), Bagbazar GPA: 3.35 / 4.0	2020 – 2022
Bachelor of Science in Information Technology (BSIT) - Data Science, 	2023 – 2027
Kings College, Kathmandu (Affiliated with Westcliff University, California)
Currently in 4th Year  GPA: 3.54 / 4.0
TECHNICAL SKILLS Languages :  Python · SQL	Data Analysis : Pandas · NumPy · Excel
Data Visualization:  Matplotlib · Seaborn · Power 	Tools: Git & GitHub BI
Currently Learning: Neural Networks · Deep 
Machine Learning : Scikit-learn · PyTorch	Learning · Computer Vision 
PROJECTS Chini — Diabetes Risk Predictor for Women
       Python · Pandas · NumPy · Matplotlib · Seaborn · Scikit-learn · SciPy · Streamlit · Docker
       GitHub: https://github.com/suyogkarki1/diabetes_pipeline.git  
       Live: https://chinisugar.streamlit.app/  
  Built a diabetes risk predictor for adult women•	 on the Pima Indians dataset (768 records), using a scikitlearn pipeline that fills in missing values and scales features, so it works even with incomplete patient data.
  Ran •	Welch's t-tests comparing diabetic vs non-diabetic patients, using the t-statistic and p-value (α = 0.05) to judge significance and Cohen's d for effect size, to find which measurements best separate the two groups.
  Compared five models with 5-fold cross-validation and tuned each with GridSearchCV (including•	 
L1/L2/ElasticNet regularization for Logistic Regression), keeping all preprocessing inside the folds to prevent data leakage.
  Chose•	 Logistic Regression and scored on PR-AUC instead of accuracy because the data is imbalanced, reaching 0.81 ROC-AUC, 73% accuracy, and 0.72 recall on the test set.
  Deployed it as an interactive Streamlit web app, containerized with Docker for easy setup.•
Kathmandu Rain Prediction
       Python · Pandas · NumPy · Scikit-learn · Matplotlib · Seaborn · Streamlit 
       GitHub: https://github.com/suyogkarki1/Rain-Prediction-    Live: https://barshamausam.streamlit.app/  
  Sourced a 10-year Kathmandu weather dataset (2015–2025, 3,468 records) from Kaggle, and performed data•	 cleaning, unit conversion, and feature engineering across 14 meteorological variables for supervised classification.
  Built and evaluated four classification models Logistic Regression, Decision Tree, K-Nearest Neighbors, and•	 Random Forest  using stratified 6-fold cross-validation; selected Random Forest as the final model, achieving 84% accuracy and 0.90 ROC-AUC on held-out test data.
  Conducted feature importance analysis identifying •	humidity, temperature, and cloud cover as the strongest rainfall predictors, validating the model against real-world Kathmandu Valley monsoon patterns.
  Applied •	bootstrap resampling to estimate 2026 monthly rain probabilities with lower and upper uncertainty bounds, and developed a separate SARIMA seasonal time-series model to forecast monthly rainy-day percentages for comparison.
  Deployed the trained model as an interactive Streamlit web application •	(SkyCast) enabling real-time rain classification from user-defined weather inputs and visualizing seasonal forecast trends.
Customer Churn Prediction
        Python · Pandas · Scikit-learn · Matplotlib · Seaborn
       GitHub : https://github.com/suyogkarki1/customer-churn-prediction  
  Analyzed a Kaggle dataset of 10,000 European bank customers to identify behavioral patterns linked to•	 churn, including credit score, account balance, and product usage habits.
  Engineered new features including •	BalancePerProduct and AgeGroup; conducted full EDA to uncover class imbalance and key churn indicators before applying preprocessing steps.
  Achieved •	86.35% accuracy and 0.87 ROC-AUC using Gradient Boosting Classifier, selected after benchmarking against simpler models including Logistic Regression and Decision Tree.
  Feature importance analysis revealed •	Age and NumOfProducts as the strongest churn predictors — suggesting retention teams should prioritize older single-product customers as the highest risk segment
Smart Healthcare and Lifestyle Prediction
        Python · Pandas · Scikit-learn · Matplotlib · Seaborn
       GitHub : https://github.com/suyogkarki1/Smart-Healthcare-and-Lifestyle-Prediction  
  Worked with a Kaggle healthcare dataset of•	 5,000 patient records with clinical indicators like blood pressure, cholesterol, BMI, smoking habits, and chest pain severity.
  Ran a full pipeline data cleaning, EDA, feature analysis, model training, and evaluation using a •	stratified train/test split to keep the class balance the same, and compared several models before choosing Logistic Regression.
  The data was •	imbalanced, so I used class_weight='balanced' and looked at PR-AUC and recall, not just accuracy, since accuracy can be misleading on imbalanced data.
  Got 99.4% accuracy and 0.999 ROC-AUC, but I didn't fully trust these numbers — scores this high usually•	 mean the data is cleanly separated or synthetic, not real-world skill. I used cross-validation to check there was no data leakage in my pipeline..
UAE ID Card Number Extraction Pipeline
        Python · YOLOv11 (Ultralytics) · OpenCV · Tesseract OCR · PostgreSQL
        Github: https://github.com/suyogkarki1/object_detection.git  
  Annotated a custom dataset of 424 UAE ID card images on Ultralytics HUB, labeling the ID-number field as a•	 dedicated detection class, split into 405 train / 10 validation / 9 test images.
  Trained and deployed a custom YOLOv11 model via Ultralytics' hosted endpoint, achieving •	99.5% mAP50 and 95.0% recall on ID-number localization.
  Built an OCR pipeline (OpenCV preprocessing + Tesseract) to extract and clean detected ID numbers via•	 regex, then persisted records to PostgreSQL with conflict-safe deduplication.
QR Code Validator Using Finite Automata
Python · Graphviz · Deterministic Finite Automata
Github: https://github.com/suyogkarki1/qr-code-authentication.git  
  Built a system that validates QR code data using a Deterministic Finite Automaton (DFA), checking the•	 bitstream structure step by step and accepting or rejecting based on whether it reaches a valid end state.
  Parsed and extracted structured information from valid codes, handling two formats bank payment QRs•	 (account name, number, type) and WiFi QRs (SSID, password).
Generated DFA state diagrams with Graphviz to visualize the validation flow.•
Applied theory-of-computation concepts (finite automata) to a practical data-validation problem•
LANGUAGES Nepali	Englis Native	Fluent
'''

In [3]:
#tokenization 
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
tokens = word_tokenize(document.lower().replace(',', '').replace('·', ''))

In [5]:
#vocab
vocab={'<unk>':0}
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]=len(vocab)

In [34]:
len(vocab)

532

In [7]:
# extract sentences  from data 
input_sentences=document.split('\n')


In [8]:
print(input_sentences)

['SUYOG KARKI', 'PROFILE Data Science Intern Candidate  | ML & Analytics suyogkarki2@gmail.com \t \t+977 9860103707 \t \tTokha, Kathmandu linkedin.com/in/suyog-karki-8544a033a \t \tgithub.com/suyogkarki1 \t \tsuyogkarki1.com.np ', "EDUCATION Data Science student experienced in building end-to-end machine learning projects using Python, SQL, and Scikit-learn covering data cleaning, EDA, feature engineering, statistical testing, preprocessing pipeline, crossvalidation, hyperparameter tuning, and model evaluation. Applied this across projects in weather forecasting, customer churn, and healthcare risk. I'm genuinely curious about AI and machine learning, and I want to keep getting better at it — looking for a data science/ML or analytics internship to learn and grow.", 'Higher Secondary Education (+2) - Science, ', 'Kathmandu Model College (KMC), Bagbazar GPA: 3.35 / 4.0\t2020 – 2022', 'Bachelor of Science in Information Technology (BSIT) - Data Science, \t2023 – 2027', 'Kings College, Ka

In [9]:
print(input_sentences[1])

PROFILE Data Science Intern Candidate  | ML & Analytics suyogkarki2@gmail.com 	 	+977 9860103707 	 	Tokha, Kathmandu linkedin.com/in/suyog-karki-8544a033a 	 	github.com/suyogkarki1 	 	suyogkarki1.com.np 


In [10]:
def text_to_indices(sentences,vocab):
    numerical_sentences=[]
    
    for token in sentences:
        if token in vocab:
            numerical_sentences.append(vocab[token])
        else:
            numerical_sentences.append(vocab['<unk>'])
            
    return numerical_sentences

In [11]:
input_numerical_sentences=[]
for sentences in input_sentences:
    
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentences.lower()),vocab))


In [12]:
input_numerical_sentences

[[1, 2],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0, 18, 19, 20, 21],
 [22,
  4,
  5,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  0,
  33,
  0,
  34,
  35,
  36,
  4,
  37,
  0,
  38,
  0,
  39,
  40,
  0,
  41,
  42,
  0,
  43,
  44,
  0,
  45,
  0,
  46,
  47,
  0,
  34,
  48,
  49,
  50,
  51,
  52,
  53,
  30,
  25,
  54,
  55,
  0,
  56,
  57,
  0,
  34,
  58,
  59,
  50,
  60,
  61,
  62,
  63,
  64,
  65,
  34,
  28,
  29,
  0,
  34,
  60,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  4,
  77,
  78,
  11,
  79,
  67,
  80,
  34,
  81,
  50],
 [82, 83, 22, 84, 85, 86, 87, 5, 0],
 [18, 48, 88, 84, 89, 86, 0, 90, 91, 92, 93, 94, 95, 96, 97, 98],
 [99, 100, 5, 25, 101, 102, 84, 103, 86, 87, 4, 5, 0, 104, 97, 105],
 [106, 88, 0, 18, 84, 107, 108, 109, 110, 0, 111, 86],
 [112, 25, 113, 114, 91, 92, 115, 94, 95],
 [116, 117, 118, 92, 32, 0, 33, 4, 119, 92, 120, 0, 121, 0, 122],
 [4, 123, 92, 124, 0, 125, 0, 126, 127, 92, 128, 10, 12

In [13]:
input_sentences[4]

'Kathmandu Model College (KMC), Bagbazar GPA: 3.35 / 4.0\t2020 – 2022'

In [14]:
len(input_numerical_sentences)

59

In [15]:
training_sequences=[]
for sentences in input_numerical_sentences:
    
    for i in range(1,len(sentences)):
        training_sequences.append(sentences[:i+1])

In [16]:
len(training_sequences)

1076

In [17]:
training_sequences[:5]

[[1, 2], [3, 4], [3, 4, 5], [3, 4, 5, 6], [3, 4, 5, 6, 7]]

In [18]:
#training sequences has 1076 input sequences but there are of different size so 
# if we send this input training model cant give one input sentences 
#for that we use padding to make same size 
#like how ?  above we can we [3,4],[3,4,5] we add 0 infront of [3,4]=[0,3,4] now [0,3,4]=[3,4,5] same size 

In [19]:
longest_list=[]

for sequences in training_sequences:
    longest_list.append(len(sequences))
max(longest_list)

90

In [20]:
#now we need to make all the training sequences into 89 to make same size   
# padding for batch processing 

In [21]:
padded_training_sequences=[]
for sequences in training_sequences:
    padded_training_sequences.append([0]*( max(longest_list)-len(sequences)) + sequences)

In [22]:
len(padded_training_sequences[89])

90

In [23]:
padded_training_sequences=torch.tensor(padded_training_sequences,dtype=torch.long)

In [24]:
padded_training_sequences.shape

torch.Size([1076, 90])

In [25]:
X=padded_training_sequences[:, :-1]
y=padded_training_sequences[:,-1]

In [26]:
X.shape

torch.Size([1076, 89])

In [33]:
y.shape

torch.Size([1076])

In [28]:
from typing import Any

from torch.utils.data import DataLoader,Dataset

class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X=X
        self.y=y
    
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, index):
        
        return self.X[index],self.y[index]

In [29]:
dataset=CustomDataset(X,y)

In [30]:
len(dataset)

1076

In [31]:
dataLoader=DataLoader(dataset,batch_size=32,shuffle=True)

In [32]:
for input,output in dataLoader:
    print(input,output)

tensor([[  0,   0,   0,  ..., 218, 151, 219],
        [  0,   0,   0,  ...,   0,   0,  30],
        [  0,   0,   0,  ..., 274, 275, 270],
        ...,
        [  0,   0,   0,  ..., 394, 456, 457],
        [  0,   0,   0,  ...,   0, 479, 480],
        [  0,   0,   0,  ..., 397, 209, 210]]) tensor([220, 137, 271, 244,  57, 152, 292, 159,  34, 343,  97, 185, 386,   0,
         34, 227,  34, 152, 373, 365,  34, 262, 492,   0, 235,  67, 284, 227,
        153, 458, 481,  50])
tensor([[  0,   0,   0,  ..., 372, 373, 329],
        [  0,   0,   0,  ..., 108, 143,  75],
        [  0,   0,   0,  ...,  90,  91,  92],
        ...,
        [  0,   0,   0,  ..., 171, 272, 393],
        [  0,   0,   0,  ...,   0, 514,  86],
        [  0,   0,   0,  ...,  49,  50,  51]]) tensor([235, 241,  93,   0, 152,  34, 272,  10,  50,   0, 173, 339,  48, 124,
         34,  34,  51,   0,  86,  86, 173,  76, 498,  34,   0, 125, 309, 238,
        530, 394,  34,  52])
tensor([[  0,   0,   0,  ...,  88,   0,  18],
    

In [ ]:
class LSTM(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding=nn.Embedding(vocab_size,100)
        self.lstm=nn.LSTM(100,150,batch_first=True)
        self.fc=nn.Linear(150,vocab_size)
        
    def forward(self):
    